input_style="\[${reset}\]"
ruby_format="\[${reset}${yellow}\]"
user_name="\[${reset}${bold}${red}\]\u"
at_symbol="\[${reset}${bold}${light_gray}\]@"
machine_name="\[${reset}${bold}${orange}\]\h"
location_word="\[${reset}${bold}${light_gray}\] in "
location_path="\[${reset}${bold}${blue}\]\w"
user_privilege="\[${reset}${bold}${white}\]\n\$"
